### ISSUE TITLE
아이디 찾기 & 비밀번호 찾기 ViewController UI짜기

### ISSUE THREAD

**Issue by rlarldud1234** [AppS01u7E/SNS_IOS#7]
## 개요

> 아이디 찾기 뷰컨트롤러와 비밀번호 찾기 뷰컨트롤ㄹ러 유아이 짜기

## 작업 내용

- [ ] 아이디 찾기 뷰컨트롤러 유아이 짜기
- [ ] 비밀번호 찾기 뷰 컨트롤러 유아이 짜기

## 참고사항

오늘안에 짜기

**Comment by kimdaehee0824** [comment]
잘 만들었슴, 이슈 닫아도 되나요?
